import type { Part, PartTheme } from './types';

const themes: Record<Part['id'], PartTheme> = {
  P1: {
    accentText: 'text-rose-600',
    accentBg: 'bg-rose-500',
    softGradient: 'from-rose-50 via-orange-50 to-amber-50',
    ring: 'ring-rose-400',
    badge: 'bg-rose-100 text-rose-700 border-rose-200',
  },
  P2: {
    accentText: 'text-sky-600',
    accentBg: 'bg-sky-500',
    softGradient: 'from-sky-50 via-cyan-50 to-blue-50',
    ring: 'ring-sky-400',
    badge: 'bg-sky-100 text-sky-700 border-sky-200',
  },
  P3: {
    accentText: 'text-amber-600',
    accentBg: 'bg-amber-500',
    softGradient: 'from-amber-50 via-yellow-50 to-orange-50',
    ring: 'ring-amber-400',
    badge: 'bg-amber-100 text-amber-800 border-amber-200',
  },
  P4: {
    accentText: 'text-violet-600',
    accentBg: 'bg-violet-500',
    softGradient: 'from-violet-50 via-purple-50 to-fuchsia-50',
    ring: 'ring-violet-400',
    badge: 'bg-violet-100 text-violet-700 border-violet-200',
  },
  P5: {
    accentText: 'text-emerald-600',
    accentBg: 'bg-emerald-500',
    softGradient: 'from-emerald-50 via-teal-50 to-green-50',
    ring: 'ring-emerald-400',
    badge: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  },
  P6: {
    accentText: 'text-indigo-600',
    accentBg: 'bg-indigo-500',
    softGradient: 'from-indigo-50 via-blue-50 to-slate-50',
    ring: 'ring-indigo-400',
    badge: 'bg-indigo-100 text-indigo-700 border-indigo-200',
  },
  P7: {
    accentText: 'text-pink-600',
    accentBg: 'bg-pink-500',
    softGradient: 'from-pink-50 via-rose-50 to-red-50',
    ring: 'ring-pink-400',
    badge: 'bg-pink-100 text-pink-700 border-pink-200',
  },
  P8: {
    accentText: 'text-slate-700',
    accentBg: 'bg-slate-600',
    softGradient: 'from-slate-50 via-zinc-50 to-gray-50',
    ring: 'ring-slate-400',
    badge: 'bg-slate-100 text-slate-700 border-slate-200',
  },
  CONSENT: {
    accentText: 'text-zinc-800',
    accentBg: 'bg-zinc-900',
    softGradient: 'from-zinc-50 via-white to-stone-50',
    ring: 'ring-zinc-500',
    badge: 'bg-zinc-100 text-zinc-700 border-zinc-200',
  },
};

export const parts: Part[] = [
  {
    id: 'P1',
    index: 1,
    title: 'Part 1. 응답자 프로필',
    subtitle: '먼저 당신에 대해 알려주세요',
    description: '학년·성별·지역 등 기본 정보를 묻습니다. 5문항.',
    theme: themes.P1,
    questionIds: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5'],
  },
  {
    id: 'P2',
    index: 2,
    title: 'Part 2. 현재 학습 환경',
    subtitle: '지금 어떻게 공부하고 있나요?',
    description: '사교육 형태·공부시간·비용·만족도. 5문항.',
    theme: themes.P2,
    questionIds: ['Q6', 'Q7', 'Q8', 'Q9', 'Q10'],
  },
  {
    id: 'P3',
    index: 3,
    title: 'Part 3. 학습의 어려움',
    subtitle: '공부하면서 답답했던 순간을 알려주세요',
    description: '학습 중 가장 큰 장애물을 진단합니다. 6문항.',
    theme: themes.P3,
    questionIds: ['Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16'],
  },
  {
    id: 'P4',
    index: 4,
    title: 'Part 4. AI 학습도구 경험',
    subtitle: 'AI를 공부에 써본 적이 있나요?',
    description: '생성형 AI 사용 경험과 느낀 점. 5문항.',
    theme: themes.P4,
    questionIds: ['Q17', 'Q18', 'Q19', 'Q20', 'Q21'],
  },
  {
    id: 'P5',
    index: 5,
    title: 'Part 5. 문답식 학습법에 대한 태도',
    subtitle: '"왜?" 라고 묻는 학습은 어떤가요?',
    description: '질문 기반 학습에 대한 인식. 3문항 + 순위 1문항.',
    theme: themes.P5,
    questionIds: ['Q22', 'Q23', 'Q24', 'Q25'],
  },
  {
    id: 'P6',
    index: 6,
    title: 'Part 6. 신규 AI 튜터 서비스 관심도',
    subtitle: '새로운 AI 튜터, 사용해 보고 싶나요?',
    description: '서비스 컨셉에 대한 관심과 사용 맥락. 5문항.',
    theme: themes.P6,
    questionIds: ['Q26', 'Q27', 'Q28', 'Q29', 'Q30'],
  },
  {
    id: 'P7',
    index: 7,
    title: 'Part 7. 가격 민감도',
    subtitle: '얼마면 쓸 만하다고 느낄까요?',
    description: 'Van Westendorp 기반 가격 인식. 5문항.',
    theme: themes.P7,
    questionIds: ['Q31', 'Q32', 'Q33', 'Q34', 'Q35'],
  },
  {
    id: 'P8',
    index: 8,
    title: 'Part 8. 자유 의견',
    subtitle: '마지막으로 하고 싶은 이야기',
    description: '서비스에 바라는 점과 자유 의견. 4문항.',
    theme: themes.P8,
    questionIds: ['Q36', 'Q37', 'Q38', 'Q39'],
  },
  {
    id: 'CONSENT',
    index: 9,
    title: '개인정보 수집·이용 동의',
    subtitle: '제출 전 마지막 단계입니다',
    description: '응답자 확인·사은품 발송을 위한 정보만 수집합니다.',
    theme: themes.CONSENT,
    questionIds: [],
  },
];

export const partById = Object.fromEntries(parts.map((p) => [p.id, p])) as Record<
  Part['id'],
  Part
>;
